### ISSUE TITLE
Building Kodo-Python from source - asks for github username - private?

### ISSUE THREAD

**Issue by sreekrishnapandi** [steinwurf/kodo-python#26]
While running
`python waf configure` , 
during "resolving dependency for kodo", it asks for username..
```
ubuntu@ip-xxxxxxxxxxxx:~/Downloads/kodo-python$ python waf configure
Setting top to                           : /home/ubuntu/Downloads/kodo-python 
Setting out to                           : /home/ubuntu/Downloads/kodo-python/build/linux 
Checking for program 'git'               : ['/usr/bin/git'] 
Resolve dependency sak                   : /home/ubuntu/Downloads/kodo-python/bundle_dependencies/sak-1bdcea/13.0.0 
Resolve dependency kodo                  : Username for 'https://github.com': 
```

When provided with username and password, it throws the following error : 
````
Command ['/usr/bin/git', 'clone', 'https://github.com/steinwurf/kodo.git', '/home/ubuntu/Downloads/kodo-python/bundle_dependencies/kodo-879b21/master'] returned 128
```

Is "kodo" repository made private (accidentally) ?

**Comment by tsleepy** [comment]
But I have a license. And I am getting the same error

**Comment by petya2164** [comment]
@tsleepy Our logs indicate that you have not accepted our invitation to access the Kodo repo.
Please accept it and try again!
You should be able to clone Kodo itself with this command:
`git clone https://github.com/steinwurf/kodo.git`

**Comment by tsleepy** [comment]
Thanks it worked..But now it's giving another error. It can't find a C++ compiler.
I have MSVS 2013 express edition installed..and set the system environment path 'VS90COMNTOOLS' to 'C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\Tools\'
I have also tried with MinGW and Cygwin but no luck :(

**Comment by petya2164** [comment]
@tsleepy Did you install the 32-bit version of Python 2.7 as we recommend?
MinGW and Cygwin are not supported, so don't waste your time with those.

**Comment by tsleepy** [comment]
@petya2164 Yes I downloaded the 32-bit version of python 2.7 and MS Visual studio 2013 Express edition. I'm using Windows 8.1

**Comment by petya2164** [comment]
@tsleepy Could you share your config.log? Most likely it is saved to build/windows/config.log.
Sharing files is not possible here, so you can send an email to our mailing list: <steinwurf-dev@googlegroups.com> with the attachment.

**Comment by tsleepy** [comment]
Sure will do that!!
In a few hours may b. Don't have the laptop with me right now!
Thanks a lot!

**Comment by tsleepy** [comment]
@petya2164  Hi the reinstallation VS13 worked. now the python is configured and built but the kodo.so file is not there!! I can't understand what I am doing wrong!!

**Comment by jpihl** [comment]
On windows the resulting file will have the extension ``.pyd`` and not ``.so``.. Are you able to find a ``kodo.pyd`` file?

**Comment by tsleepy** [comment]
yes, it's there :)

*Tarjina Islam*
*Student Assistant at Vodafone Chair Mobile Communications Systems*
*Technische Universität Dresden*
*Dresden, Germany*
*E-mail: tarjina@gmail.com <tarjina@gmail.com>; **tarjina.islam@tu-dresden.de
<tarjina.islam@tu-dresden.de>*
*Phone: +4917680813101 <%2B4917680813101>*

**Comment by jpihl** [comment]
Well I think congratulations are in order! :tada: :wink: 
Let us know if you have any other issues..
