### ISSUE TITLE
Multicast crash

### ISSUE THREAD

**Issue by fischermario** [steinwurf/kodo-python#32]
We have implemented a simplified version of the multicast examples. If we run them locally everything goes just fine. But if we try to execute them on a real network (infrastructure or ad-hoc wifi) we always run into trouble like this: the receiver never completes its job (it is stuck at rank x) or fails completely with a crash. This seems to happen randomly.

Just to rule out some common problems we have added MD5 hashing for each file to make sure we really transmit different packets.

See the following files:
https://gist.github.com/fischermario/98ff4be900cb141bdd8a

**Comment by jpihl** [comment]
Hi Mario,

This is very odd. It seems like you lose some packets on the real network, but that shouldn't cause any issues.
I haven't  been able to replicate the error though, so I can't do much to fix the issue.
I'll take a second look if you can provide me with a self-contained example illustrating the issue.

**Comment by sreekrishnapandi** [comment]
Hi Mario,
I have a baseless suggestion. Can you check if both computers run the same version of KODO? 
I can see from the log file that that the receiver is running v22.1.0. 
`python: /tmp/pip_build_root/kodo/kodo-python/bundle_dependencies/kodo-879b21/22.1.0/src/kodo/bidirectional_linear_block_d.... 
Aborted (core dumped)`
Check if the sender is also running the same. 
Maybe it doesn't matter. But I cant think of anything else why it wouldn't work over the Network.
