### ISSUE TITLE
AttributeError in lena.py

### ISSUE THREAD

**Issue by tsleepy** [steinwurf/kodo-python#39]
I am trying to run the lena.py in local machine. After installing pygame, numpy and PIL everytime I am getting the following error:
Traceback (most recent call last):
  File "lena.py", line 118, in <module>
    main()
  File "lena.py", line 82, in main
    data_in = image.tobytes()
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 512, in __getattr__
    raise AttributeError(name)
AttributeError: tobytes

the image lena.jpg is in the same folder of lena.py

**Comment by jpihl** [comment]
Your issue seems to be related to this https://github.com/asciimoo/drawille/issues/9
A quick fix would be to replace ``data_in = image.tobytes()`` with ``data_in = image.tostring()`` in line 82 in your lena.py file. I'm not sure how a more permanent one would look.

**Comment by tsleepy** [comment]
@jpihl thanks a lot!! the problem is solved

**Comment by jpihl** [comment]
Glad I could help :+1:
