### ISSUE TITLE
Is systematic coding also applied to recoding?

### ISSUE THREAD

**Issue by r-s-s** [steinwurf/kodo-python#41]
With using the Python recoding example as a base I try to realize the following:

    Encoder -----> Recoder -----> Decoder
        |                            |
        ------------------------------
		  
Basically decoding from either encoded or recoded symbols. But when I use the trace to follow the Decoder state I see that sets of coefficients appear twice, with an encoded and a recoded packet, which leads to the assumption that the recoder doesn't use a new random encoding vector.
The factories are FullVectorDe/EncoderFactoryBinary8Trace and for the encoder systematic coding is disabled.

Code snippet:
```Python
while not recoder.is_complete():
	# Encode a packet into the payload buffer
	packet = encoder.encode()
	packet_list.append(packet)

	# Pass that packet to recoder
	recoder.decode(packet)

packet_count = 0	
while not decoder.is_complete():
	if random.choice([True, False]):
		print "recoded packet"
		packet = recoder.recode()
		decoder.decode(packet)
	else:
		print "encoded packet"
		packet = packet_list[packet_count]
		decoder.decode(packet)
		packet_count += 1
```

Example output:
```
encoded packet
input_symbol_coefficients:
C: 140 151 183 216 154 219

decoder_state:
000 C:  1 15 189 112 175 133
001 ?:  0 0 0 0 0 0
002 ?:  0 0 0 0 0 0
003 ?:  0 0 0 0 0 0
004 ?:  0 0 0 0 0 0
005 ?:  0 0 0 0 0 0

recoded packet
input_symbol_coefficients:
C: 140 151 183 216 154 219

decoder_state:
000 C:  1 15 189 112 175 133
001 ?:  0 0 0 0 0 0
002 ?:  0 0 0 0 0 0
003 ?:  0 0 0 0 0 0
004 ?:  0 0 0 0 0 0
005 ?:  0 0 0 0 0 0

encoded packet
input_symbol_coefficients:
C: 139 216 108 159 165 98

decoder_state:
000 C:  1 0 255 126 216 130
001 C:  0 1 95 151 9 197
002 ?:  0 0 0 0 0 0
003 ?:  0 0 0 0 0 0
004 ?:  0 0 0 0 0 0
005 ?:  0 0 0 0 0 0

recoded packet
input_symbol_coefficients:
C: 139 216 108 159 165 98

decoder_state:
000 C:  1 0 255 126 216 130
001 C:  0 1 95 151 9 197
002 ?:  0 0 0 0 0 0
003 ?:  0 0 0 0 0 0
004 ?:  0 0 0 0 0 0
005 ?:  0 0 0 0 0 0
```

**Comment by petya2164** [comment]
@r-s-s You fill up your recoder before using it, so essentially your recoder becomes a second encoder operating on the same data. Therefore you could implement this with 2 encoders!
Most likely, the encoder and the recoder generate the same pseudo-random vectors, because they use the same random seed by default. That's why you see the same sequence. Unfortunately, there is no function in the Python API to change the random seed. Although you could easily do this in C++.
We will expose this function in a future version or we will just pick a random seed every time you create an encoder/decoder ;)

**Comment by petya2164** [comment]
@r-s-s We just updated to Kodo 26 that randomizes the seeds for each encoder/decoder. You can just update your kodo-python to the latest version and rebuild it.
I noticed that you are using the old API in your example code: we no longer have encode/decode/recode methods. Check our examples when you update your code.

**Comment by r-s-s** [comment]
Thank you for that fast fix! Updating to the last version and just changing to read_/write_payload now leads to working examples.
