### ISSUE TITLE
choose the number of symbol and the size of symbol?

### ISSUE THREAD

**Issue by lxkaka** [steinwurf/kodo-python#42]
hello, 
I am using kodo encode the file and send to the client. Must I choose proper number of symbol and the size of symbol as the size of the file？and when should I stop the encoding? The example shows 'while true'
Thanks a lot!

**Comment by petya2164** [comment]
@lxkaka You can choose the number of symbols/symbol_size as you wish. You can split the input data to multiple, smaller generations if you like. Our example might be too simple for your use case.
You can use feedback from the decoder to stop sending encoded packets. Alternatively, you can just "overshoot": e.g. send more packets than the number of symbols and adjust this quantity based on the expected packet loss in your network..
