### ISSUE TITLE
small file after coding get much bigger

### ISSUE THREAD

**Issue by lxkaka** [steinwurf/kodo-python#44]
hello, I send a pdf file with 2.5MB to the receiver, and I use multiple to transfer this file. Evey time I read 1024KB and encode (symbols = 110 , symbol_size = 10000)  When the  process finish, the reciver obtain the file. But it has size with more than 400MB.  Theoretically it should be with size 3.3MB.
what can be the problem?

**Comment by petya2164** [comment]
@lxkaka Can you share your code with us? It is really difficult to give any advice without that.
Your calculation is correct: if one generation is 110 * 10000  bytes = 1.1 MB, then 3 generations should be 3.3 MB. I should also warn you that your 10000-byte symbol size is too large for a common network, the packets will be fragmented. The MTU is usually 1500 bytes, so your encoded packets should fit into that.
In this example, we use 1400 bytes:
https://github.com/steinwurf/kodo-python/blob/master/examples/multicast_sender_example.py
Maybe you should start with receiving a single generation to verify that your code is correct.

**Comment by lxkaka** [comment]
@petya2164  Thanks for your quick reply.  Actually I send the same file in a single generation with symbols=260,symbol_size= 10000 is successful. I choose large symbol_size, because I want to reduce the number of symbols, so that can reduce the processing time. And Because I must transfer large file to test performance,so I must split the file into multiple.

**Comment by lxkaka** [comment]
@petya2164 I found the size of received file is equal number of generated packet * symbols*symbol_numbers.
This is my code:https://github.com/lxkaka/TCP-NC/blob/master/TCP_NC_Server1.py
https://github.com/lxkaka/TCP-NC/blob/master/TCP_NC_Client1.py

**Comment by mortenvp** [comment]
@lxkaka Can you explain your calculation above what is generated packet, symbols, symbol_numbers?

**Comment by petya2164** [comment]
@lxkaka Here is your issue:
https://github.com/lxkaka/TCP-NC/blob/master/TCP_NC_Client1.py#L77
Whenever you receive a packet, you append the whole generation to an existing file ;)
You should write a generation only once, when the decoding is completed for that generation. And you can append to that file when the next generation is decoded.

**Comment by lxkaka** [comment]
@mortenvp  symbols is the small segment of the file, I mean symbol_numbers is the symbol_size. sorry I typed wrong. And generated packet is the encoded symbol. Is my understanding right?

**Comment by petya2164** [comment]
@lxkaka Sure, the generated packet contains an encoded symbol.
Could you solve the issue based on my suggestions?

**Comment by lxkaka** [comment]
@petya2164  I am very thankful for your correcting. I think that is the point. But some wrong come up with my kodo update, I try to solve the problem lately.

**Comment by lxkaka** [comment]
@petya2164  I have fixed the problem. Thank you very much ;)
