### ISSUE TITLE
When installing kodo on Ubuntu 14.04, installing process stuck with 108/109.

### ISSUE THREAD

**Issue by amazing814** [steinwurf/kodo-python#45]
Hello, everyone:
now I am trying to install Kodo on my laptop, using Ubuntu 14.04.
following the steps as:

sudo apt-get update
sudo apt-get install python git build-essential libpython-dev
sudo pip install kodo

it's quite clear to see , there are 109 packages to be installed, but the programm seems to be stopped after the 108th package installed:
![mmexport1429562531431](https://cloud.githubusercontent.com/assets/11939306/7240055/a3ca2b44-e7ae-11e4-9659-96e33ad1028f.jpg)

some one told me, sometimes when the RAM of computer is not enough, it can take a day to finish the last step.... My labtop's RAM is 3.4GB available....so.....

I decide to keep my compute running for a whole night, but I don't think that will work. Is there anyone knows what should I do now?  thanks a lot.

**Comment by amazing814** [comment]
I guess I should learn to be patient. 
After 1 hour the install-process is successfully finished. 
I'm happy~ Thank you all the same~
Hu P P

**Comment by petya2164** [comment]
Indeed, this issue seems to be frustrating for many people, so we will try to restructure kodo-python to bring down the RAM usage and the compilation time.
FYI, it is the g++ optimizer that is eating up all your RAM in the process.

**Comment by amazing814** [comment]
@petya2164 keep moving ! thank you for you gays effort~

**Comment by petya2164** [comment]
@amazing814 You wanted to write "guys" ;)))) Be careful with English spelling!

**Comment by amazing814** [comment]
@petya2164 :lol....sorry~
