### ISSUE TITLE
The difference between sliding window and full vector

### ISSUE THREAD

**Issue by lxkaka** [steinwurf/kodo-python#47]
hello
I think I should use sliding window encode my data, so that I can compare the performance coded TCP and regular TCP. Can you explain the the difference between sliding window and full vector?

**Comment by mortenvp** [comment]
Hi @lxkaka,
Lets say you choose the number of symbols to be 16 (this is also called the generation size). A full vector code will encode over all 16 symbols when you created a coded packet.

A sliding window code differs in two main ways:
1) You can add symbols "on-the-fly". Lets say you initially do not have all 16 symbols available, but only 5. With sliding window you can still create a coded packet, but it will just only include those 5 packets.
2) You can send feedback from the decoder to the encoder. This feedback contains information about the state of the decoder. The encoder uses this to remove packets from the "coding window" which have already been "seen" at the decoder.

I think those are the two key points.

**Comment by lxkaka** [comment]
@mortenvp Thank you for your explain. Based on your explain I think that sliding-window can mainly reduce the computation. For TCP in lossy condition I think full-vector encoding also can promote the performance. Is that correct?

**Comment by petya2164** [comment]
Well, you will not see any packet losses with TCP!
I don't think that you can gain anything by using RLNC over TCP.
What are you trying to achieve?

**Comment by lxkaka** [comment]
@petya2164￼ ￼
![2015-04-21 6 01 06](https://cloud.githubusercontent.com/assets/10549664/7256629/805fc2a2-e850-11e4-81a7-ec721558d0d0.png)
That is my purpose.

**Comment by petya2164** [comment]
So you want TCP over NC, not NC over TCP! That is a huge difference!
Are you implementing a UDP-based protocol to replace normal TCP? Is that your project?
Then you will have to forget TCP sockets like this:
https://github.com/lxkaka/TCP-NC/blob/master/TCP_Client.py#L10
This does not make any sense with NC.

**Comment by lxkaka** [comment]
@petya2164  That's so sad. I must think about my plan.
I set packet loss rate with 5%, through wireshark I can't see duplicate ACKs if I use I TCP_NC. And compare with loss rate 0 the transmission time increased not too much. 
That's the example, TCP_NC : 0 loss  152 s
                                TCP_NC :  5% loss  181s
                                 regular TCP : 0 loss 1.6 s
                                 regular TCP: 5% loss 6.6 s

**Comment by petya2164** [comment]
Before moving forward, you can improve your fundamental knowledge about TCP and ARQ.

I will close this issue now, since it was not an actual issue with kodo-python.
In the future, please use our mailing list (steinwurf-dev@googlegroups.com) for asking question like this!
