### ISSUE TITLE
systematic coding

### ISSUE THREAD

**Issue by lxkaka** [steinwurf/kodo-python#48]
hello,
If we encode with systematic coding, the encoded packet does not include all the data which in the source file. what is the exact mean of systematic coding?

**Comment by petya2164** [comment]
@lxkaka You can read about the various Kodo features in our manual: http://kodo-docs.steinwurf.com/en/latest/overview.html
You should also read our FAQ: http://kodo-docs.steinwurf.com/en/latest/faq.html
The systematic packets contain the data from the next source symbol and some information in the packet header. To send a full block in systematic mode, you just have to send as many packets as the number of symbols in that block.

In the future, please ask questions like this on our mailing list, steinwurf-dev@googlegroups.com!
This is not an issue but a question ;)
