### ISSUE TITLE
under kodo-python/examples running "python lena.py" but not work.

### ISSUE THREAD

**Issue by amazing814** [steinwurf/kodo-python#49]
Hello everyone, lately I have installed kodo-python. 
Today I was trying to use the examples of kodo-python. It works well as "python encode_decode_simple.py "
![image](https://cloud.githubusercontent.com/assets/11939306/7458450/dc9d6d82-f294-11e4-9c53-71d045849983.png)
 
but when I use " python lena.py", it at first reminds me to install pygame. After installation of pygame:
![image](https://cloud.githubusercontent.com/assets/11939306/7458489/1499dfe0-f295-11e4-9565-1a8882827686.png)

It says: AttributeError: 'FullVectorDecoderBinary8' object has no attribute 'trace'

If there is anyone can tell me what have I missed to install ?
thx~

**Comment by petya2164** [comment]
It looks like you are using the latest version of the examples with an older version of kodo-python.
I think you will have to update and rebuild the library:
```
cd kodo-python
git pull
python waf configure
python waf build
```

**Comment by amazing814** [comment]
@petya2164 Okey, I will try ! thx at first~

**Comment by amazing814** [comment]
@petya2164  I have tried, but it still not works.
![image](https://cloud.githubusercontent.com/assets/11939306/7514541/8b0bdf36-f4be-11e4-8875-ea36ec828e2b.png)

Is it because that I have no python-config ? I tried to install something named "python-config", there is no such filed from my source. then I tried the "software center" as follows:
![image](https://cloud.githubusercontent.com/assets/11939306/7514563/d3dfa7ce-f4be-11e4-8eff-a1f24857b115.png)

still not working. and the report is the same as before~

**Comment by petya2164** [comment]
@amazing814 Do you get the same error message?
python-config is not a problem here, since you can compile the code.
It might be that pygame is not compatible with Python 2.7 :(
Can you try to run the `use_trace_layers.py` example? (It uses the same "trace" function)

**Comment by petya2164** [comment]
You should also check if you copied the latest kodo.so to your PYTHONPATH from: `build/linux/src/kodo_python/kodo.so`

Furthermore, you can run our official unit tests with:
`python waf --options=run_tests`
And you can post the console output here.

**Comment by amazing814** [comment]
@petya2164 :
I have tried the use_trace_layer.py. And the output is the same with lean.py. as follows:
![image](https://cloud.githubusercontent.com/assets/11939306/7525924/c33974fa-f50d-11e4-944e-0aafb840adfa.png)

I have used "export PYTHONPATH=/home/huzheng/kodo-python/build/linux/src/kodo-python" 22 to build the path already.
then I tried the  python waf -- options=run_tests, the  output is as follows:
![image](https://cloud.githubusercontent.com/assets/11939306/7525901/8a658b14-f50d-11e4-9344-d949e9385270.png)

Sorry for bothering you so many times~ thx as always~

**Comment by petya2164** [comment]
You should execute the tests in kodo-python, not in kodo :)
Why do you even have kodo installed?

And it still looks like you have an old version of kodo.so in your PYTHONPATH, which uses the old version of FullVectorEncoderBinary8. Can you find and remove all kodo.so files from your system?

**Comment by amazing814** [comment]
@petya2164 : I have just removed the kodo.so file(there is only one~),and used the 'python waf configure'and 'python waf build' to build the new kodo.so file.
then I used 'export PYTHONPATH=/home/huzheng/kodo-python/build/linux/src/kodo-python/kodo.so' to make the path.
then I ran the 'python waf --options=run_tests', and the program works good~ as follows:
![image](https://cloud.githubusercontent.com/assets/11939306/7526469/0c9015ba-f512-11e4-8606-f8e8a2ad4f21.png)

but, still, the 'python lena.py' and 'python use_trace_layers.py ' works bad:
![image](https://cloud.githubusercontent.com/assets/11939306/7526505/625d255a-f512-11e4-9327-b0a1ca38ef06.png)


about the 'Python', I was asked to install 'kodo' 'kodo-python' and 'fifi-python' at the very beginning~ so.... maybe some days later, I may use 'kodo' without python....I guess~

**Comment by petya2164** [comment]
LOL, the trace function works with lena.py if you run the tests! Without the trace, you would not see the picture!
This means that your "normal" python environment is corrupted, and you are not using the right version of kodo-python.
Perhaps you have installed kodo-python with pip and you forgot about it?
Can you show us the output of the `pip list` command?
Btw, you don't have to send these large screenshot, just copy the text from the terminal. Thank you!

**Comment by amazing814** [comment]
@petya2164 :
adium-theme-ubuntu (0.3.4)
apt-xapian-index (0.45)
argparse (1.2.1)
chardet (2.0.1)
colorama (0.2.5)
command-not-found (0.3)
compizconfig-python (0.9.11.3)
configglue (1.1.2)
configobj (4.7.2)
configparser (3.3.0r2)
debtagshw (0.1)
defer (1.0.6)
dirspec (13.10)
docutils (0.11)
duplicity (0.6.23)
epydoc (3.0.1)
html5lib (0.999)
httplib2 (0.8)
kodo (7.0.0)
lockfile (0.8)
lxml (3.3.3)
numpy (1.8.2)
oauthlib (0.6.1)
oneconf (0.3.7)
PAM (0.4.2)
pexpect (3.1)
Pillow (2.3.0)
pip (1.5.4)
piston-mini-client (0.7.5)
psutil (1.2.1)
pycrypto (2.6.1)
pycups (1.9.66)
pycurl (7.19.3)
pygame (1.9.1release)
Pygments (1.6)
pygobject (3.12.0)
pyOpenSSL (0.13)
pyserial (2.6)
pysmbc (1.0.14.1)
python-apt (0.9.3.5ubuntu1)
python-debian (0.1.21-nmu2ubuntu2)
pytz (2012c)
pywapi (0.3.6)
pyxdg (0.25)
reportlab (3.0)
requests (2.2.1)
roman (2.0.0)
sessioninstaller (0.0.0)
setuptools (3.3)
six (1.5.2)
software-center-aptd-plugins (0.0.0)
system-service (0.1.6)
Twisted-Core (13.2.0)
Twisted-Web (13.2.0)
ubuntu-kylin-software-center (0.2.9)
Unidecode (0.04.14)
unity-china-photo-scope (1.0)
unity-lens-photos (1.0)
urllib3 (1.7.1)
urwid (1.1.1)
wheel (0.24.0)
wsgiref (0.1.2)
xdiagnose (3.6.3build2)
zope.interface (4.0.5)

is that what you want?

**Comment by petya2164** [comment]
Yes, you have to uninstall the "kodo" pip package:
`sudo pip uninstall kodo`
The pip package takes precedence, because it is installed into the core Python folders. You had no chance to override it with the module that you compiled :(
I'm closing this issue now.

**Comment by amazing814** [comment]
@petya2164 problem solved! thank you very much~ then I can enjoy some programs now~ :)
