### ISSUE TITLE
Cloning URL not set correctly

### ISSUE THREAD

**Issue by Janluak** [steinwurf/kodo-python#50]
> python waf configure:
> Command ['/usr/bin/git', 'clone', 'git@github.com:steinwurf/kodo.git', '/path/to/directory/kodo-python/bundle_dependencies/kodo-f3a9b9/master'] returned 128

I tried to configure and got the error above. Obviously the URL setting isn't correct.
kodo-python.git instead of kodo.git

**Comment by jpihl** [comment]
Hi @Janluak, this repository contains language bindings for the main kodo project. So the configurations script is doing the right thing by pulling the code from that repository.
The reason why it's failing is that you do not yet have access to the main kodo project. As stated in the README for this project you need to have a license to use it.

Please sign up for a license here (our script is currently offline but it should be back soon): http://steinwurf.com/license/

Kind regards

jpihl

**Comment by jpihl** [comment]
@Janluak you can get a license here: https://docs.google.com/forms/d/1slthJ-LGD12XopeXrr4C-98-iArjQ_8XVdJx-pjD3rg/viewform?hl=en
